<html>
<head>
<title>TestNG:  App1Test</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>App1Test</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>7/2/2</td>
</tr><tr>
<td>Started on:</td><td>Tue Mar 15 23:45:59 CDT 2022</td>
</tr>
<tr><td>Total time:</td><td>254 seconds (254929 ms)</td>
</tr><tr>
<td>Included groups:</td><td>regression sanity runall </td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl()'><b>selectProduct_validateSelectUrl</b><br>Test class: com.qa.tests.FinologyHomeTest<br>Test method: This test is to validate Select App url</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Select url is not as expected:  expected [https://select.finology.in1/] but found [//https://select.finology.india/]
	at com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl(FinologyHomeTest.java:167)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace46627301", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace46627301'><pre>java.lang.AssertionError: The following asserts failed:
	Select url is not as expected:  expected [https://select.finology.in1/] but found [//https://select.finology.india/]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl(FinologyHomeTest.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre></div></td>
<td>7</td>
<td>com.qa.tests.FinologyHomeTest@4313f5bc</td></tr>
<tr>
<td title='com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl()'><b>tickerProduct_validateTickerUrl</b><br>Test class: com.qa.tests.FinologyHomeTest<br>Test method: This test is to validate Ticker App url<br/>
<a href="#Output-1107404311" onClick='toggleBox("Output-1107404311", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1107404311" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1107404311">
This Test is to validate ticker App url which is a new window<br/>
Fail - Finology Url is NOT as expected<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Finology url is not as expected:  expected [https://www.finology.in/] but found [https://www.finology.india/]
	at com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl(FinologyHomeTest.java:114)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1107404311", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1107404311'><pre>java.lang.AssertionError: The following asserts failed:
	Finology url is not as expected:  expected [https://www.finology.in/] but found [https://www.finology.india/]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl(FinologyHomeTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre></div></td>
<td>6</td>
<td>com.qa.tests.FinologyHomeTest@4313f5bc</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailDuplicateTest()'><b>finologyLoginByEmail_EmailDuplicateTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: anvardhan551@gmail.com, Pnbe@305, iteration1<br/>
<a href="#Output-2075352262" onClick='toggleBox("Output-2075352262", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-2075352262" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-2075352262">
This isiteration1of this test<br/>
</div>
</td>
<td></td>
<td>14</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailDuplicateTest()'><b>finologyLoginByEmail_EmailDuplicateTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: 7799096333, Pnbe@305, iteration2<br/>
<a href="#Output-239648666" onClick='toggleBox("Output-239648666", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-239648666" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-239648666">
This isiteration2of this test<br/>
</div>
</td>
<td></td>
<td>13</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailDuplicateTest()'><b>finologyLoginByEmail_EmailDuplicateTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: anvardhan551@gmail.com, Pnbe@305, iteration1<br/>
<a href="#Output-281896787" onClick='toggleBox("Output-281896787", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-281896787" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-281896787">
This isiteration1of this test<br/>
</div>
</td>
<td></td>
<td>13</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailTest()'><b>finologyLoginByEmail_EmailTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: anvardhan551@gmail.com, Pnbe@305, iteration1<br/>
<a href="#Output-1566311673" onClick='toggleBox("Output-1566311673", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1566311673" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1566311673">
This isiteration1of this test<br/>
</div>
</td>
<td></td>
<td>13</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailTest()'><b>finologyLoginByEmail_EmailTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: 7799096333, Pnbe@305, iteration2<br/>
<a href="#Output-373682836" onClick='toggleBox("Output-373682836", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-373682836" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-373682836">
This isiteration2of this test<br/>
</div>
</td>
<td></td>
<td>12</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByEmail_EmailTest()'><b>finologyLoginByEmail_EmailTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: anvardhan551@gmail.com, Pnbe@305, iteration1<br/>
<a href="#Output-1842476600" onClick='toggleBox("Output-1842476600", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1842476600" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1842476600">
This isiteration1of this test<br/>
</div>
</td>
<td></td>
<td>14</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
<tr>
<td title='com.qa.tests.FinologyLoginTest.finologyLoginByPhoneTest()'><b>finologyLoginByPhoneTest</b><br>Test class: com.qa.tests.FinologyLoginTest<br>Parameters: 7799096333, Pnbe@305</td>
<td></td>
<td>13</td>
<td>com.qa.tests.FinologyLoginTest@7f010382</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-skipped'>
<tr><td colspan='4' align='center'><b>SKIPPED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl()'><b>selectProduct_validateSelectUrl</b><br>Test class: com.qa.tests.FinologyHomeTest<br>Test method: This test is to validate Select App url</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Select url is not as expected:  expected [https://select.finology.in1/] but found [//https://select.finology.india/]
	at com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl(FinologyHomeTest.java:167)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace814245389", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace814245389'><pre>java.lang.AssertionError: The following asserts failed:
	Select url is not as expected:  expected [https://select.finology.in1/] but found [//https://select.finology.india/]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at com.qa.tests.FinologyHomeTest.selectProduct_validateSelectUrl(FinologyHomeTest.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre></div></td>
<td>7</td>
<td>com.qa.tests.FinologyHomeTest@4313f5bc</td></tr>
<tr>
<td title='com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl()'><b>tickerProduct_validateTickerUrl</b><br>Test class: com.qa.tests.FinologyHomeTest<br>Test method: This test is to validate Ticker App url<br/>
<a href="#Output-1693997031" onClick='toggleBox("Output-1693997031", this, "Show output", "Hide output");'>Show output</a>

<a href="#Output-1693997031" onClick="toggleAllBoxes();">Show all outputs</a>
<div class='log' id="Output-1693997031">
This Test is to validate ticker App url which is a new window<br/>
Fail - Finology Url is NOT as expected<br/>
</div>
</td>
<td><div><pre>java.lang.AssertionError: The following asserts failed:
	Finology url is not as expected:  expected [https://www.finology.in/] but found [https://www.finology.india/]
	at com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl(FinologyHomeTest.java:114)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1693997031", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1693997031'><pre>java.lang.AssertionError: The following asserts failed:
	Finology url is not as expected:  expected [https://www.finology.in/] but found [https://www.finology.india/]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
	at com.qa.tests.FinologyHomeTest.tickerProduct_validateTickerUrl(FinologyHomeTest.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:770)
	at org.testng.TestRunner.run(TestRunner.java:591)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1175)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
	at org.testng.TestNG.runSuites(TestNG.java:1032)
	at org.testng.TestNG.run(TestNG.java:1000)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre></div></td>
<td>6</td>
<td>com.qa.tests.FinologyHomeTest@4313f5bc</td></tr>
</table><p>
</body>
</html>